### ISSUE TITLE
Issue With importing lens/utils

### ISSUE THREAD

**Issue by ExtremelySeriousChicken** [adigunhammedolalekan/go-contacts#1]
Hi,

I have an issue with trying to run the tutorial. When I run the program, I got the error "lens/utils" is not recognized in auth.go, accounts.go, and contacts.go . Is the line supposed to be 

u "go-contacts/utils"? Thanks

**Comment by adigunhammedolalekan** [comment]
Exactly, it was suppose to be `u "go-contacts/utils"` lens is another project located in my machine's GOPATH, that was why i didn't notice the error.

**Comment by mkopa** [comment]
@adigunhammedolalekan hi, I solved this problem and create pull request. Btw. thanks for good articles on Medium.
