### ISSUE TITLE
Add License?

### ISSUE THREAD

**Issue by dhill2522** [adigunhammedolalekan/go-contacts#5]
Hi!

Thank you for your very informative and helpful medium article on building REST APIs with Golang and JWT. 

I noticed that your repository does not have a license and is thus technically illegal for others to use even though it appears that you wanted it openly available. More information can be found [here](https://choosealicense.com/no-permission/). Would you mind adding a standard open source license so that other can use it as well? I would recommend using the MIT license unless you have a reason to use something else. 

I would be happy to make a pull request for this if that would be easier for you.

Thanks!
Daniel Hill

**Comment by adigunhammedolalekan** [comment]
Hi @dhill2522 
Thanks for bringing this to my notice. Please throw in the PR, Thanks once again.
