### ISSUE TITLE
Remove .idea from the repository

### ISSUE THREAD

**Issue by Spacehug** [adigunhammedolalekan/go-contacts#7]
Although you do have `.idea` in .gitignore, it should be `.idea/` to ignore whole .idea directory.
Also, it is in the repository, and I reckon it should not be there.

PS Mind if I do a bit of a cleanup? IMO, .env is a bit off the standard, and I would like to go fmt all the codebase

**Comment by adigunhammedolalekan** [comment]
@SpaceBug you can do the cleanup as long as the original source code is not modified. Thanks

**Comment by dejanstrancar** [comment]
@adigunhammedolalekan @Spacehug ive created PR: https://github.com/adigunhammedolalekan/go-contacts/pull/8
